---

- hosts: all
  become: yes


  pre_tasks:
    - name: Update apt cache
      apt: >
        upgrade=yes
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - include: setup.yml


  handlers:
    - name: restart docker daemon
      service: >
           name=docker
           state=restarted
